
[Energy_Capacity]
	#Range: 0 ~ 9000000000000000000
	starterCap = 0
	#Range: 0 ~ 9000000000000000000
	basicCap = 0
	#Range: 0 ~ 9000000000000000000
	hardenedCap = 0
	#Range: 0 ~ 9000000000000000000
	blazingCap = 0
	#Range: 0 ~ 9000000000000000000
	nioticCap = 0
	#Range: 0 ~ 9000000000000000000
	spiritedCap = 0
	#Range: 0 ~ 9000000000000000000
	nitroCap = 0

[Energy_Transfer]
	#Range: 0 ~ 9000000000000000000
	starterTransfer = 4000
	#Range: 0 ~ 9000000000000000000
	basicTransfer = 20000
	#Range: 0 ~ 9000000000000000000
	hardenedTransfer = 60000
	#Range: 0 ~ 9000000000000000000
	blazingTransfer = 360000
	#Range: 0 ~ 9000000000000000000
	nioticTransfer = 1800000
	#Range: 0 ~ 9000000000000000000
	spiritedTransfer = 6000000
	#Range: 0 ~ 9000000000000000000
	nitroTransfer = 240000000

[Channels]
	#Range: 1 ~ 12
	starterChannels = 1
	#Range: 1 ~ 12
	basicChannels = 2
	#Range: 1 ~ 12
	hardenedChannels = 3
	#Range: 1 ~ 12
	blazingChannels = 5
	#Range: 1 ~ 12
	nioticChannels = 7
	#Range: 1 ~ 12
	spiritedChannels = 9
	#Range: 1 ~ 12
	nitroChannels = 12

