
[Energy_Capacity]
	#Range: 0 ~ 9000000000000000000
	starterCap = 5000
	#Range: 0 ~ 9000000000000000000
	basicCap = 25000
	#Range: 0 ~ 9000000000000000000
	hardenedCap = 100000
	#Range: 0 ~ 9000000000000000000
	blazingCap = 500000
	#Range: 0 ~ 9000000000000000000
	nioticCap = 1000000
	#Range: 0 ~ 9000000000000000000
	spiritedCap = 2500000
	#Range: 0 ~ 9000000000000000000
	nitroCap = 8000000

[Energy_Transfer]
	#Range: 0 ~ 9000000000000000000
	starterTransfer = 50
	#Range: 0 ~ 9000000000000000000
	basicTransfer = 150
	#Range: 0 ~ 9000000000000000000
	hardenedTransfer = 300
	#Range: 0 ~ 9000000000000000000
	blazingTransfer = 700
	#Range: 0 ~ 9000000000000000000
	nioticTransfer = 1000
	#Range: 0 ~ 9000000000000000000
	spiritedTransfer = 2000
	#Range: 0 ~ 9000000000000000000
	nitroTransfer = 4000

[Energy_Generation]
	#Range: 0 ~ 9000000000000000000
	starterGeneration = 10
	#Range: 0 ~ 9000000000000000000
	basicGeneration = 24
	#Range: 0 ~ 9000000000000000000
	hardenedGeneration = 54
	#Range: 0 ~ 9000000000000000000
	blazingGeneration = 120
	#Range: 0 ~ 9000000000000000000
	nioticGeneration = 270
	#Range: 0 ~ 9000000000000000000
	spiritedGeneration = 600
	#Range: 0 ~ 9000000000000000000
	nitroGeneration = 2400

